# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f902aa11900d68eb0c0e882296ee5993dd2cc6c8b7277b7e7621912dc9c5a68ee2f9ca1fda9466bb3202475c0e2826dd2bae84b03ff02d3022a5876a771fb7d

test:
  secret_key_base: 52e93a06472961461d4796684d009bc89304a7987312d43bb1c62d1eeae7f9822eb2bfd3b8282a1711da56ced4b3ed69532e0d880472e82e2cb1335e5daa46ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
